### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by witchfindertr** [radyhaggag/tiktok_downloader#1]
https://www.tiktok.com/@phunog779/video/7167498985240792347?is_from_webapp=1&sender_device=pc&web_id=7098082912931530242

Bad state: Cannot add new events after calling close

When the exception was thrown, this was the stack: 
#1      Bloc.add (package:bloc/src/bloc.dart:99:24)
#2      _DownloaderScreenState._buildBodyDownloadBtn.<anonymous closure> (package:tiktok_downloader/src/features/tiktok_downloader/presentation/screens/downloader_screen.dart:165:42)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#21     _invoke1 (dart:ui/hooks.dart:167:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided one frame from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#f5522
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(198.2, 607.2)
  finalLocalPosition: Offset(100.0, 11.8)
  button: 1
  sent tap down

**Comment by radyhaggag** [comment]
This problem occurred because I make downloader bloc as static variable, but i had fixed it and update the repo you can try now.

**Comment by witchfindertr** [comment]
> This problem occurred because I make downloader bloc as static variable, but i had fixed it and update the repo you can try now.

now working perfect. congratulations
